version: '3.8'
services:
  api:
    build: ./pythonapp
    ports:
      - "5000:5000"
    environment:
      - POLYGON_API_KEY=${POLYGON_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    networks:
      - app-network

  web:
    build: ./nextapp
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://api:5000
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge